workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - firebase_credentials
    scripts:
      - name: Get Flutter packages
        script: |
          echo "get flutter packages"
          flutter packages pub get
      - name: Install pods
        script: |
          echo "install pods"
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter Analyze
        script: |
          echo "flutter analyze"
          flutter analyze
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - yucel.ilke@gmail.com
        notify:
          success: true
          failure: false
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        ios:
          app_id: 1:364593885285:ios:58c4a463b7152396b5568c
          groups:
            - iosTesters
